name: "Update-Rules-Wiki"
description: "Updates the carpet rules in the appropriate wiki page."
inputs:
  event-name:
    description: "The name of the event that triggered the workflow."
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout Carpet sources
      uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        distribution: "adopt"
        java-version: 21
        cache: "gradle"
    - name: Checkout wiki
      uses: actions/checkout@v4
      with:
        repository: ${{github.repository}}.wiki
        path: wiki
    - name: Create wiki page
      shell: bash
      run: |
        chmod +x gradlew
        ./gradlew runServer --args="-- -carpetDumpRules -dumpPath '../wiki/Available-Rules.md' -dumpFilter carpet-addons-not-found"
        sed -i '1d' wiki/Available-Rules.md # Removes title from page
    - name: Commit updated wiki page
      continue-on-error: true
      shell: bash
      run: |
        cd wiki
        git config --global user.name 'github-actions-bot' # Releases don't have valid commiter info :(
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add Available-Rules.md
        git commit -m "Update wiki for '${{ inputs.event-name }}'" || exit 0
        git push
