name: Update Wiki Job
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-rules-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update wiki
        uses: ./.github/actions/update-wiki
        with:
          event-name: "manual-trigger"
