name: Pull Request Builds

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: 17
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build with gradle
        run: ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: "Compiled artifacts for Pull Request #${{github.event.number}}"
          path: build/libs
