name: Pull Request Builds

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build project
        uses: ./.github/actions/build-action
        with:
          artifact-name: PR-${{ github.event.number }}
